root: true
env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
parser: babel-eslint
rules:
  no-unused-vars: [off]
overrides:
  - files: ['*.test.js']
    env:
      jest: true
