root: true
env:
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
parser: babel-eslint
rules:
  no-unused-vars: [off]
overrides:
  - files: ['*.test.js']
    env:
      node: true
      jest: true
    rules:
      no-undef: [off]
